import { createFileRoute } from "@tanstack/react-router";
import { HeartHandshake, Lightbulb, MessageCircle, SearchCheck } from "lucide-react";
import { InquiryForm, CascadeTitle, MapPanel, PageHero, Reveal, SectionHeading, whatsappUrl } from "@/components/luxora";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [
  { title: "À propos & Contact | Luxora Voyages" }, { name: "description", content: "Découvrez l’approche Luxora et confiez-nous votre projet de voyage, déplacement ou expérience." },
  { property: "og:title", content: "À propos & Contact | Luxora Voyages" }, { property: "og:description", content: "Une écoute attentive pour un voyage profondément personnel." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: ContactPage });
function ContactPage(){return <><PageHero eyebrow="À propos & Contact" title="Une personne derrière chaque voyage." intro="Luxora est née d’une conviction simple : les plus belles expériences commencent par une vraie écoute." motif="contact"/><section className="section"><div className="grid gap-14 lg:grid-cols-2"><Reveal><SectionHeading eyebrow="L’approche Luxora" title="Présente, attentive, exigeante dans les détails." text="Nous prenons le temps de comprendre ce qui compte pour vous. Puis nous cherchons, sélectionnons et assemblons chaque élément avec créativité et précision."/><div className="mt-10 grid gap-6 sm:grid-cols-3"><Value icon={<SearchCheck/>} label="Écoute"/><Value icon={<Lightbulb/>} label="Créativité"/><Value icon={<HeartHandshake/>} label="Accompagnement"/></div></Reveal><Reveal><MapPanel/></Reveal></div></section><section className="section bg-secondary"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.65fr_1.35fr]"><Reveal><p className="eyebrow">Votre projet</p><CascadeTitle text="Dites-nous où vous souhaitez aller." className="mt-4 font-display text-5xl" /><p className="mt-5 leading-7 text-muted-foreground">Nous vous répondons avec une première lecture de votre demande et les prochaines étapes.</p><Button asChild variant="outline" className="mt-7"><a href={whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle className="h-4 w-4"/>Écrire sur WhatsApp</a></Button></Reveal><Reveal className="form-panel"><InquiryForm /></Reveal></div></section></>}
function Value({icon,label}:{icon:React.ReactNode;label:string}){return <div className="border-t border-primary pt-4"><div className="text-primary [&>svg]:h-5 [&>svg]:w-5">{icon}</div><p className="mt-4 font-display text-2xl">{label}</p></div>}