import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Compass, Sailboat, Trees, UtensilsCrossed, Waves } from "lucide-react";
import { PageHero, Reveal, SectionHeading } from "@/components/luxora";
import { Button } from "@/components/ui/button";
import { useState } from "react";

export const Route = createFileRoute("/experiences")({ head: () => ({ meta: [
  { title: "Excursions & Expériences | Luxora Voyages" }, { name: "description", content: "Safaris, sorties en bateau, gastronomie, bien-être et expériences privées à réserver seules ou avec votre séjour." },
  { property: "og:title", content: "Excursions & Expériences | Luxora" }, { property: "og:description", content: "Vivez la destination autrement." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: ExperiencesPage });
const experiences=[{category:"Nature",place:"Zanzibar",title:"Safari bleu privé",duration:"Journée",icon:Waves},{category:"Nature",place:"Tanzanie",title:"Safari au lever du jour",duration:"2 jours",icon:Trees},{category:"Gastronomie",place:"Rome",title:"Rome à table",duration:"4 heures",icon:UtensilsCrossed},{category:"Culture",place:"Marrakech",title:"Médina confidentielle",duration:"Demi-journée",icon:Compass},{category:"Mer",place:"Paris",title:"Dîner privé sur la Seine",duration:"3 heures",icon:Sailboat},{category:"Bien-être",place:"Zanzibar",title:"Rituel bien-être face à l’océan",duration:"2 heures",icon:Waves}];
function ExperiencesPage(){const [filter,setFilter]=useState("Toutes");const categories=["Toutes","Nature","Gastronomie","Culture","Mer","Bien-être"];const shown=filter==="Toutes"?experiences:experiences.filter(x=>x.category===filter);return <><PageHero eyebrow="Excursions & Expériences" title="Vivez la destination autrement." intro="Des moments choisis avec soin, à réserver seuls ou à intégrer naturellement dans votre séjour Luxora." motif="experience"/><section className="section"><Reveal><SectionHeading eyebrow="Collection" title="Choisissez une émotion, nous créons le moment."/></Reveal><div className="mt-10 flex flex-wrap gap-2" role="group" aria-label="Filtrer les expériences">{categories.map(c=><Button key={c} variant={filter===c?"primary":"outline"} size="sm" onClick={()=>setFilter(c)}>{c}</Button>)}</div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{shown.map(({title,place,duration,category,icon:Icon},index)=><Reveal key={title} className={`experience-card tone-${index%3}`}><div className="experience-visual"><Icon className="h-12 w-12" strokeWidth={1}/><span>{place}</span></div><div className="p-6"><p className="text-[0.68rem] font-bold uppercase tracking-[0.16em] text-primary">{category} · {duration}</p><h3 className="mt-3 font-display text-3xl">{title}</h3><Button asChild variant="ghost" className="mt-5 px-0"><Link to="/contact">Demander un devis <ArrowRight className="h-4 w-4"/></Link></Button></div></Reveal>)}</div></section></>}