import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Gift, Heart, Map, Utensils, Wand2 } from "lucide-react";
import { CascadeTitle, PageHero, Reveal, SectionHeading } from "@/components/luxora";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/voyages")({ head: () => ({ meta: [
  { title: "Voyages sur mesure & Luxora Signature" }, { name: "description", content: "Itinéraires personnalisés, Travel Planner, lunes de miel et voyages Signature conçus dans les moindres détails." },
  { property: "og:title", content: "Voyages sur mesure & Signature | Luxora" }, { property: "og:description", content: "Votre voyage, imaginé autour de vous." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: VoyagesPage });
function VoyagesPage(){ const planner=[[Map,"Programme jour par jour"],[Utensils,"Tables & bonnes adresses"],[Wand2,"Expériences adaptées"],[ArrowRight,"Transferts fluides"]] as const; return <><PageHero eyebrow="Voyages & Séjours" title="Votre voyage, imaginé autour de vous." intro="Billets, hôtels, circuits, séjours en couple ou en famille : nous construisons une proposition qui vous ressemble." motif="voyage" />
<section className="section"><div className="grid gap-14 lg:grid-cols-2"><Reveal><SectionHeading eyebrow="Travel Planner" title="Déjà réservé ? Confiez-nous la suite." text="Nous transformons vos réservations en un itinéraire cohérent, riche et serein. Votre temps, votre budget et votre façon de voyager guident chaque choix." /><Button asChild className="mt-8"><Link to="/contact">Confier mon séjour <ArrowRight className="h-4 w-4" /></Link></Button></Reveal><div className="grid gap-px bg-border sm:grid-cols-2">{planner.map(([Icon,label])=><Reveal className="icon-card" key={label}><Icon className="h-5 w-5 text-primary"/><p className="mt-8 font-display text-2xl">{label}</p></Reveal>)}</div></div></section>
<section className="story-band"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><Reveal><p className="eyebrow text-primary">Luxora Signature</p><CascadeTitle text="Certains voyages méritent plus qu’une simple réservation." className="mt-5 max-w-4xl font-display text-5xl text-ivory lg:text-7xl" /></Reveal><div className="mt-14 grid gap-6 md:grid-cols-3"><Signature icon={<Heart/>} title="Célébrer" text="Lunes de miel, anniversaires et escapades romantiques."/><Signature icon={<Gift/>} title="Surprendre" text="Attentions personnalisées, coffrets et présentations soignées."/><Signature icon={<Wand2/>} title="Orchestrer" text="Chefs privés, chauffeurs, dîners et expériences rares."/></div><Button asChild variant="outline" className="mt-10"><Link to="/contact">Créer mon voyage Signature</Link></Button></div></section></> }
function Signature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <Reveal className="signature-card"><div className="text-primary [&>svg]:h-6 [&>svg]:w-6">{icon}</div><h3 className="mt-8 font-display text-3xl text-ivory">{title}</h3><p className="mt-3 leading-7 text-ivory/65">{text}</p></Reveal>}